Expenses.Web/Controllers/CategoryController.cs
using AutoMapper;
using Expenses.Web.Business.Extensions;
using Expenses.Web.Business.Mediator.Categories;
using Expenses.Web.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Web.Controllers
{
  [Authorize]
  public class CategoryController : Controller
  {
    private readonly IMediator mediator;
    private readonly IMapper mapper;

    public CategoryController(IMediator mediator, IMapper mapper)
    {
      this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
      this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
    }

    [HttpGet]
    public async Task<IActionResult> List(CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();
      var model = await mediator.Send(new CategoryListRequest(userId), cancellationToken);

      return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
    {
      CategoryViewModel model = null;

      if (id.HasValue)
      {
        var userId = this.GetUserId();
        model = await mediator.Send(new CategoryRequest(id.Value, userId), cancellationToken);
      }

      if (model == null)
      {
        model = new CategoryViewModel
        {
        };
      }

      return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(CategoryViewModel model, CancellationToken cancellationToken)
    {
      if (model == null)
      {
        throw new ArgumentNullException(nameof(model));
      }

      if (ModelState.IsValid)
      {
        var userId = this.GetUserId();

        var request = mapper.Map<CategoryEditRequest>(model);
        request.UserId = userId;

        await mediator.Send(request, cancellationToken);

        return RedirectToAction(nameof(List));
      }

      return View(model);
    }
  }
}

Expenses.Web/Controllers/DefaultController.cs
using Expenses.Web.Business.Extensions;
using Expenses.Web.Business.Mediator.Default;
using Expenses.Web.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Web.Controllers
{
  [Authorize]
  public class DefaultController : Controller
  {
    private readonly IMediator mediator;

    public DefaultController(IMediator mediator)
    {
      this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
    }

    [HttpGet]
    public async Task<IActionResult> Index(CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();

      var overviewByCategory = await mediator.Send(new OverviewByCategoryRequest(userId), cancellationToken);
      ViewData["overviewByCategory"] = overviewByCategory;
      ViewData["maxExpensiveCategory"] = overviewByCategory
        .OrderByDescending(it => it.Value.Debet)
        .FirstOrDefault();

      var graphData = await mediator.Send(ChartRequest.Last30Days(userId), cancellationToken);
      ViewData["lastThirtyDays"] = graphData;

      return View();
    }

    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Expenses.Web/Controllers/TransactionController.cs
using AutoMapper;
using Expenses.Web.Business.Data;
using Expenses.Web.Business.Extensions;
using Expenses.Web.Business.Mediator.Account;
using Expenses.Web.Business.Mediator.Categories;
using Expenses.Web.Business.Mediator.Transactions;
using Expenses.Web.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Web.Controllers
{
  [Authorize]
  public class TransactionController : Controller
  {
    private readonly IMediator mediator;
    private readonly IMapper mapper;

    public TransactionController(IMediator mediator, IMapper mapper)
    {
      this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
      this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
    }

    [HttpGet]
    public async Task<IActionResult> List(int page = 0, Guid? categoryId = null, bool? pending = null, CancellationToken cancellationToken = default)
    {
      var userId = this.GetUserId();

      var categories = await mediator.Send(new CategoryListRequest(userId), cancellationToken);
      ViewBag.Categories = categories;
      ViewBag.CategoryId = categoryId.HasValue ? $"{categoryId.Value}" : string.Empty;

      ViewBag.Pending = pending.HasValue && pending.Value;

      var transactions = await mediator.Send(
        new TransactionListRequest(userId)
        {
          Page = page,
          CategoryId = categoryId,
          Pending = pending
        },
      cancellationToken);

      ViewBag.Count = transactions.Count;
      ViewBag.Pages = transactions.Pages;
      ViewBag.Index = transactions.Index;

      return View(transactions.Data);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();

      TransactionViewModel model = null;

      if (id.HasValue)
      {
        model = await mediator.Send(new TransactionRequest(id.Value, userId), cancellationToken);
      }

      if (model == null)
      {
        var type = this.GetRequestValue("type");

        model = new TransactionViewModel
        {
          Type = type
        };
      }

      await CreateViewDataAsync(userId, cancellationToken);

      ViewBag.ReturnUrl = this.GetReturnUrl();

      return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(TransactionViewModel model, CancellationToken cancellationToken)
    {
      if (model == null)
      {
        throw new ArgumentNullException(nameof(model));
      }

      var userId = this.GetUserId();
      var returnUrl = this.GetReturnUrl();

      if (ModelState.IsValid)
      {
        var request = mapper.Map<TransactionEditRequest>(model);
        request.UserId = userId;

        await mediator.Send(request, cancellationToken);

        if (string.IsNullOrEmpty(returnUrl))
        {
          return RedirectToAction(nameof(List));
        }
        else
        {
          if (Url.IsLocalUrl(returnUrl))
          {
            return Redirect(returnUrl);
          }
          else
          {
            throw new InvalidOperationException("Boo !");
          }
        }
      }

      await CreateViewDataAsync(userId, cancellationToken);

      return View(model);
    }

    private async Task CreateViewDataAsync(Guid userId, CancellationToken cancellationToken)
    {
      var accounts = await mediator.Send(new AccountListRequest(userId), cancellationToken);
      ViewData.Add("accounts", accounts);

      var categories = await mediator.Send(new CategoryListRequest(userId), cancellationToken);
      ViewData.Add("categories", categories);

      var types = Enum.GetNames(typeof(TransactionType)).ToList();
      ViewData.Add("types", types);
    }
  }
}

Expenses.Web/Controllers/UserController.cs
using AutoMapper;
using Expenses.Web.Business.Mediator.User;
using Expenses.Web.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Web.Controllers
{
  [Authorize]
  public class UserController : Controller
  {
    private readonly IMediator mediator;
    private readonly IMapper mapper;

    public UserController(IMediator mediator, IMapper mapper)
    {
      this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
      this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
    }

    #region Registration
    [HttpGet]
    [AllowAnonymous]
    public IActionResult Register()
    {
      return View(new RegistrationViewModel());
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register(RegistrationViewModel model, CancellationToken cancellationToken)
    {
      if (model == null)
      {
        throw new ArgumentNullException(nameof(model));
      }

      if (ModelState.IsValid)
      {
        var request = mapper.Map<RegistrationRequest>(model);
        var result = await mediator.Send(request, cancellationToken);
        if (result == null)
        {
          throw new InvalidOperationException();
        }

        if (result.Success)
        {
          return RedirectToAction(nameof(Login), new { userName = model.UserName });
        }
        else
        {
          ModelState.AddModelError("", result.Message);
        }
      }

      return View(model);
    }
    #endregion

    #region Login

    [HttpGet]
    [AllowAnonymous]
    public IActionResult Login(string userName = "", string returnUrl = "")
    {
      var model = new LoginViewModel
      {
        UserName = userName,
        ReturnUrl = returnUrl
      };

      return View(model);
    }

    [HttpPost]
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(LoginViewModel model, CancellationToken cancellationToken)
    {
      if (model == null)
      {
        throw new ArgumentNullException(nameof(model));
      }

      if (ModelState.IsValid)
      {
        var request = mapper.Map<LoginRequest>(model);
        var user = await mediator.Send(request, cancellationToken);
        if (user == null)
        {
          ModelState.AddModelError("", "Neplatné meno, alebo heslo.");
        }
        else
        {
          var claims = new List<Claim>
          {
            new Claim(ClaimTypes.NameIdentifier, $"{user.Id}"),
            new Claim(ClaimTypes.Name, user.UserName),
            new Claim(ClaimTypes.GivenName, user.FullName)
          };

          var claimsIdentity = new ClaimsIdentity(claims, "password");
          var claimsPrinciple = new ClaimsPrincipal(claimsIdentity);
          var properties = new AuthenticationProperties
          {
            ExpiresUtc = DateTime.UtcNow.AddHours(12)
          };

          await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrinciple, properties);

          if (Url.IsLocalUrl(model.ReturnUrl))
          {
            return Redirect(model.ReturnUrl);
          }
          return Redirect("~/");
        }
      }

      return View(model);
    }

    #endregion

    #region Logout
    [HttpGet]
    public async Task<IActionResult> Logout()
    {
      await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

      return RedirectToAction(nameof(Login), new { ReturnUrl = "~/" });
    }
    #endregion
  }
}

Expenses.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Expenses Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Default" asp-action="Index">&euro;xpMgr</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mr-auto flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Default" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="List">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="List">Accounts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="List">Transactions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StandingOrder" asp-action="List">Standing orders</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav ml-auto flex-shrink-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout (@User.Identity.Name)</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - Expenses Manager by Juraj Suchán
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Expenses.Web/Views/Shared/_OverviewByCategory.cshtml
@model Dictionary<string, Expenses.Web.Business.Mediator.Default.Overview>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th></th>
            <th>Credit</th>
            <th>Debet</th>
        </tr>
    </thead>
    <tbody>
        @{
            var credits = 0m;
            var creditsWithoutPending = 0m;
            var debets = 0m;
            var debetsWithoutPending = 0m;
        }

        @foreach (var key in Model.Keys)
        {
            var item = Model[key];

            credits += item.Credit;
            creditsWithoutPending += item.CreditWithoutPending;
            debets += item.Debet;
            debetsWithoutPending += item.DebetWithoutPending;

            <tr>

                <td>
                    @{
                        var keyClass = string.Empty;
                    }

                    @if (!item.ContainsPendingCredit && !item.ContainsPendingDebet)
                    {
                        keyClass = string.Empty;
                    }
                    else
                    {
                        if (item.ContainsPendingCredit)
                        {
                            keyClass = "text-green";
                        }
                        else if (item.ContainsPendingDebet)
                        {
                            keyClass = "text-red";
                        }
                        else
                        {
                            keyClass = "text-orange";
                        }
                    }

                    <span class="@keyClass">@key</span>
                </td>

                <td>@Math.Round(item.Credit, 2)</td>
                <td>@Math.Round(item.Debet, 2)</td>
            </tr>
        }
        <tr>
            <td>
                <strong>Sum</strong>
            </td>
            <td>@Math.Round(credits, 2)</td>
            <td>@Math.Round(debets, 2)</td>
        </tr>
        <tr>
            <td>
                <strong>Sum without pendings</strong>
            </td>
            <td>@Math.Round(creditsWithoutPending, 2)</td>
            <td>@Math.Round(debetsWithoutPending, 2)</td>
        </tr>
        <tr>
            <td colspan="2">
                <strong>Balance</strong>
            </td>
            <td>
                @Math.Round(credits - debets, 2)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <strong>Balance without pendings</strong>
            </td>
            <td>
                @Math.Round(creditsWithoutPending - debetsWithoutPending, 2)
            </td>
        </tr>
    </tbody>
</table>