Expenses.Web/ViewModels/StandingOrderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Expenses.Web.ViewModels
{
  public class StandingOrderViewModel
  {
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public AccountViewModel Account { get; set; }

    public Guid CategoryId { get; set; }

    public CategoryViewModel Category { get; set; }

    [Required]
    public string Type { get; set; }

    [MaxLength(256)]
    public string Description { get; set; }

    [Range(0.0, double.MaxValue)] // this is weird
    //[DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
    public decimal Amount { get; set; }

    public DateTime Installment { get; set; }
  }
}

Expenses.Web/Controllers/StandingOrderController.cs
using AutoMapper;
using Expenses.Web.Business.Data;
using Expenses.Web.Business.Extensions;
using Expenses.Web.Business.Mediator.Account;
using Expenses.Web.Business.Mediator.Categories;
using Expenses.Web.Business.Mediator.StandingOrders;
using Expenses.Web.ViewModels;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Expenses.Web.Controllers
{
  [Authorize]
  public class StandingOrderController : Controller
  {
    private readonly IMediator mediator;
    private readonly IMapper mapper;

    public StandingOrderController(IMediator mediator, IMapper mapper)
    {
      this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
      this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
    }

    [HttpGet]
    public async Task<IActionResult> List(CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();

      var standingOrders = await mediator.Send(new StandingOrdersListRequest(userId), cancellationToken);

      return View(standingOrders.Data);
    }

    [HttpGet]
    public async Task<IActionResult> Proceed(Guid id, CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();

      await mediator.Send(new StandingOrderProceedRequest(id, userId), cancellationToken);

      return RedirectToAction(nameof(List));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
    {
      var userId = this.GetUserId();

      StandingOrderViewModel model = null;

      if (id.HasValue)
      {
        model = await mediator.Send(new StandingOrderRequest(id.Value, userId), cancellationToken);
      }

      if (model == null)
      {
        var type = this.GetRequestValue("type");

        model = new StandingOrderViewModel
        {
          Type = type,
          Installment = DateTime.UtcNow.AddDays(1)
        };
      }

      await CreateViewDataAsync(userId, cancellationToken);

      ViewBag.ReturnUrl = this.GetReturnUrl();

      return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(StandingOrderViewModel model, CancellationToken cancellationToken)
    {
      if (model == null)
      {
        throw new ArgumentNullException(nameof(model));
      }

      var userId = this.GetUserId();
      var returnUrl = this.GetReturnUrl();

      if (ModelState.IsValid)
      {
        var request = mapper.Map<StandingOrderEditRequest>(model);
        request.UserId = userId;

        await mediator.Send(request, cancellationToken);

        if (string.IsNullOrEmpty(returnUrl))
        {
          return RedirectToAction(nameof(List));
        }
        else
        {
          if (Url.IsLocalUrl(returnUrl))
          {
            return Redirect(returnUrl);
          }
          else
          {
            throw new InvalidOperationException("Boo !");
          }
        }
      }

      await CreateViewDataAsync(userId, cancellationToken);

      return View(model);
    }

    private async Task CreateViewDataAsync(Guid userId, CancellationToken cancellationToken)
    {
      var accounts = await mediator.Send(new AccountListRequest(userId), cancellationToken);
      ViewData.Add("accounts", accounts);

      var categories = await mediator.Send(new CategoryListRequest(userId), cancellationToken);
      ViewData.Add("categories", categories);

      var types = Enum.GetNames(typeof(TransactionType)).ToList();
      ViewData.Add("types", types);
    }
  }
}

Expenses.Web/Views/StandingOrder/Edit.cshtml
@model Expenses.Web.ViewModels.StandingOrderViewModel

@{
    ViewData["Title"] = "Edit Standing order";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @Html.HiddenFor(it => it.Id)
            @Html.Hidden("ReturnUrl", ViewBag.ReturnUrl as string)
            <div class="form-group">
                <label asp-for="AccountId" class="control-label">Account</label>
                <select asp-for="AccountId" class="form-control">
                    @foreach (var account in (List<AccountViewModel>)ViewData["accounts"])
                    {
                        <option value="@account.Id">@account.Name</option>
                    }
                </select>
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Category</label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in (List<CategoryViewModel>)ViewData["categories"])
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Type</label>
                <select asp-for="Type" class="form-control">
                    @foreach (var type in (List<string>)ViewData["types"])
                    {
                        <option value="@type">@type</option>
                    }
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label">Amount</label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Short description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Installment" class="control-label">Installment date</label>
                <input asp-for="Installment" type="date" class="form-control" />
                <span asp-validation-for="Installment" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i> Save
                </button>

                @if (string.IsNullOrEmpty(ViewBag.ReturnUrl as string))
                {
                    <a class="btn btn-light ml-1" asp-action="List">Back</a>
                }
                else
                {
                    <a class="btn btn-light ml-1" href="@ViewBag.ReturnUrl">Back</a>
                }
            </div>
        </form>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
}

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
}

Expenses.Web/Views/StandingOrder/List.cshtml
@model List<StandingOrderViewModel>
@{
    ViewData["Title"] = "Standing orders";
}
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive-md mt-3">
            <div class="standingorders-list">
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Amount</th>
                            <th>Category</th>
                            <th class="d-none d-lg-table-cell">Account</th>
                            <th>Installment date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a asp-area="" asp-controller="StandingOrder" asp-action="Edit" asp-route-id="@item.Id" class="">
                                        <i class="fa fa-edit" aria-hidden="true"></i>
                                    </a>
                                    &nbsp;
                                    <a asp-area="" asp-controller="StandingOrder" asp-action="Proceed" asp-route-id="@item.Id" class="">
                                        <i class="fa fa-wallet" aria-hidden="true"></i>
                                    </a>
                                </td>
                                <td>
                                    @{
                                        var type = Enum.Parse<Expenses.Web.Business.Data.TransactionType>(item.Type);
                                        if (type == Expenses.Web.Business.Data.TransactionType.Debet)
                                        {
                                            <text>-</text>
                                        }
                                    }

                                    <span>@Math.Round(item.Amount, 2)</span>
                                </td>
                                <td>
                                    @item.Category.Name
                                </td>
                                <td class="d-none d-lg-table-cell">
                                    @item.Account.Name
                                </td>
                                <td>
                                    @{
                                        if (item.Installment < DateTime.UtcNow)
                                        {
                                            <span class="text-red">
                                                @item.Installment.ToString("dd.MM.yyyy")
                                            </span>
                                        }
                                        else
                                        {
                                            @item.Installment.ToString("dd.MM.yyyy");
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <a class="btn btn-light" asp-area="" asp-controller="StandingOrder" asp-action="Edit">
            <i class="fa fa-plus"></i> Add
        </a>
    </div>
</div>

@section Styles {
    <link href="~/css/StandingOrder.css" rel="stylesheet" />
}

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>
}